<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="9" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-30T18:16:14 IST" name="Suite" finished-at="2021-04-30T18:23:40 IST" duration-ms="445432">
    <groups>
    </groups>
    <test started-at="2021-04-30T18:16:14 IST" name="Sign_in" finished-at="2021-04-30T18:18:32 IST" duration-ms="138155">
      <class name="Scripts.Sign_Validation">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Scripts.Sign_Validation@1992eaf4]" started-at="2021-04-30T18:16:14 IST" name="initialize" finished-at="2021-04-30T18:17:36 IST" duration-ms="81906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="Sign_in()[pri:0, instance:Scripts.Sign_Validation@1992eaf4]" started-at="2021-04-30T18:17:36 IST" name="Sign_in" finished-at="2021-04-30T18:18:21 IST" duration-ms="45314" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb: Ratings, Reviews, and Where to Watch the Best Movies & TV Shows] but found [IMDb Sign-In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb: Ratings, Reviews, and Where to Watch the Best Movies & TV Shows] but found [IMDb Sign-In]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.Sign_Validation.Sign_in(Sign_Validation.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Sign_in -->
        <test-method is-config="true" signature="Save_close()[pri:0, instance:Scripts.Sign_Validation@1992eaf4]" started-at="2021-04-30T18:18:27 IST" name="Save_close" finished-at="2021-04-30T18:18:32 IST" duration-ms="5057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Save_close -->
      </class> <!-- Scripts.Sign_Validation -->
    </test> <!-- Sign_in -->
    <test started-at="2021-04-30T18:18:34 IST" name="Get_movie" finished-at="2021-04-30T18:19:10 IST" duration-ms="35976">
      <class name="Scripts.Get_Movie">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Scripts.Get_Movie@180e6ac4]" started-at="2021-04-30T18:18:34 IST" name="initialize" finished-at="2021-04-30T18:18:38 IST" duration-ms="4045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="check_movie()[pri:0, instance:Scripts.Get_Movie@180e6ac4]" started-at="2021-04-30T18:18:38 IST" name="check_movie" finished-at="2021-04-30T18:19:08 IST" duration-ms="30059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_movie -->
        <test-method is-config="true" signature="Save_close()[pri:0, instance:Scripts.Get_Movie@180e6ac4]" started-at="2021-04-30T18:19:08 IST" name="Save_close" finished-at="2021-04-30T18:19:10 IST" duration-ms="1868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Save_close -->
      </class> <!-- Scripts.Get_Movie -->
    </test> <!-- Get_movie -->
    <test started-at="2021-04-30T18:19:10 IST" name="Create_account" finished-at="2021-04-30T18:23:40 IST" duration-ms="269523">
      <class name="Scripts.New_Account">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:19:10 IST" name="initialize" finished-at="2021-04-30T18:19:18 IST" duration-ms="8066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:19:26 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:19:53 IST" duration-ms="26924" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=adefrgt@abc.com, Results=Pass, Re_enter_PWD=abcdefg@1234, Test_Case=Valid_Values, SI_No=1, Name=desdfr, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:19:53 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:20:12 IST" duration-ms="19181" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=erttyuyu@gmail.com, Results=Pass, Re_enter_PWD=abcdefg@1234, Test_Case=Special_Name, SI_No=2, Name=Nith@anth, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:20:12 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:20:35 IST" duration-ms="22955" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=tyuyuiuiu@gmail.com, Results=Pass, Re_enter_PWD=abcdefg@1234, Test_Case=Name_20Char, SI_No=3, Name=Nithanthraiwertyunftyjnhyu, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:20:35 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:20:46 IST" duration-ms="10841" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=werrtrtrr@gmail.com, Results=Enter your name, Re_enter_PWD=abcdefg@1234, Test_Case=No_Name, SI_No=4, Name=, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:20:47 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:21:05 IST" duration-ms="18307" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=dfgvcvggr@gmail.com, Results=Pass, Re_enter_PWD=abcdefg@1234, Test_Case=Name_Less10, SI_No=5, Name=N, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:21:05 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:21:15 IST" duration-ms="9906" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=dfrrgr#$%gmail.com, Results=Enter a valid email address, Re_enter_PWD=abcdefg@1234, Test_Case=InValid_Email, SI_No=6, Name=Nithanth, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:21:15 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:21:26 IST" duration-ms="10613" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=, Results=Enter your email, Re_enter_PWD=abcdefg@1234, Test_Case=No_Email, SI_No=7, Name=Nithanth, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:21:26 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:21:45 IST" duration-ms="19305" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=lkjiuyiu12@gmail.com, Results=Pass, Re_enter_PWD=QWEWRERE@#$%WERWEREWRWERCSDF, Test_Case=PWD_20Char, SI_No=8, Name=Nithanth, Password=QWEWRERE@#$%WERWEREWRWERCSDF}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:21:45 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:22:04 IST" duration-ms="18780" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=bvnvghyf56@gmail.com, Results=Pass, Re_enter_PWD=RWERWRWRER, Test_Case=Pwd_onlychac, SI_No=9, Name=Nithanth, Password=RWERWRWRER}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:22:04 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:22:22 IST" duration-ms="18080" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=uyuytyut59@gmail.com, Results=Pass, Re_enter_PWD=1.3213232E7, Test_Case=Pwd_onlyno, SI_No=10, Name=Nithanth, Password=1.3213232E7}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:22:22 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:22:40 IST" duration-ms="18222" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=fdgfdrt546@gmail.com, Results=Pass, Re_enter_PWD=n@123, Test_Case=PWD_Less10, SI_No=11, Name=Nithanth, Password=n@123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:22:40 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:22:53 IST" duration-ms="12375" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=hjgytyu59@gmail.com, Results=Passwords must match, Re_enter_PWD=abcdefg@1234, Test_Case=no_pwd, SI_No=12, Name=Nithanth, Password=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:22:53 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:23:04 IST" duration-ms="11129" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=fsaertyiu9867@gmail.com, Results=Passwords must match, Re_enter_PWD=Nsdg@1234, Test_Case=Invalid_Repwd, SI_No=13, Name=Nithanth, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="create_account(java.util.Map)[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:23:04 IST" name="create_account" data-provider="get_data" finished-at="2021-04-30T18:23:19 IST" duration-ms="14473" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=rtetre7687@gmail.com, Results=Passwords must match, Re_enter_PWD=, Test_Case=No_Repwd, SI_No=14, Name=Nithanth, Password=abcdefg@1234}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [IMDb Registration] but found [Authentication required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [IMDb Registration] but found [Authentication required]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Scripts.New_Account.create_account(New_Account.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method is-config="true" signature="Save_close()[pri:0, instance:Scripts.New_Account@7e242b4d]" started-at="2021-04-30T18:23:19 IST" name="Save_close" finished-at="2021-04-30T18:23:40 IST" duration-ms="20627" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Save_close -->
      </class> <!-- Scripts.New_Account -->
    </test> <!-- Create_account -->
  </suite> <!-- Suite -->
</testng-results>
